#!/bin/bash

explanation='
A deep learning-based tool to identify splice variants. This tool needs NVIDIA GPU.
'
inputdef='
input_1::vcf(.gz) file:*.vcf,*.vcf.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):64
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1#"

export IM_SPLICEAI="c2997108/tensorflow:2.7.1-gpu-spliceai_2"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail


i="$input_1"
if [ `echo "$i"|grep "[.]gz$"|wc -l||true` = 1 ]; then
 zcat "$i"| DOGPU_SPLICEAI spliceai -O `basename "$i" .vcf.gz`.spliceai.vcf -R /usr/local/db/hg38/hg38.fa -A grch38
else
 cat "$i"| DOGPU_SPLICEAI spliceai -O `basename "$i" .vcf`.spliceai.vcf -R /usr/local/db/hg38/hg38.fa -A grch38
fi


post_processing

#<option detail>
#</option detail>
