#!/bin/bash

explanation='
merge 2 tables
'
inputdef='
input_1::table:*.txt,*.tsv
input_2::table:*.txt,*.tsv
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):64
opt_k:preserve headers (T or F):T
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1# #input_2#"

export IM_BASE="c2997108/centos7:1-trinity_2.8.5-kallisto_0.46.0-blast_2.9.0-trinotate-3.1.1-R_3-kegg_2"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

if [ "$opt_k" = "T" ]; then
 flag="-k"
else
 flag=""
fi

output="`basename ${input_1%.*}`.`basename ${input_2%.*}`.txt"
output2="`basename ${input_1%.*}`.`basename ${input_2%.*}`.xlsx"
DO_BASE merge_table.pl $flag "$input_1" "$input_2" > "$output"
DO_BASE java -Xmx1G -jar /usr/local/bin/excel2.jar "$output" "$output2"


post_processing

#<option detail>
#</option detail>

