#!/bin/bash

explanation='
FastANI is developed for fast alignment-free computation of whole-genome Average Nucleotide Identity (ANI).
ANI is defined as mean nucleotide identity of orthologous gene pairs shared between two microbial genomes. FastANI supports pairwise comparison of both complete and draft genome assemblies.
'
inputdef='
input_1::reference genome file:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz
input_2::target genome file:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
opt_a:FastANI options:
'
runcmd="$0 -c #opt_c# -m #opt_m# -a #opt_a# #input_1# #input_2#"

export IM_BASE="c2997108/centos7:metacor7"
export IM_FASTANI="quay.io/biocontainers/fastani:1.34--h4dfc31f_4"
export IM_GENO="c2997108/ubuntu20:R-2_gplots_genoPlotR_2"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

if [ `echo "$input_1"|grep "[.]gz$"|wc -l||true` = 1 ]; then DO_BASE gzip -dc "$input_1" > `echo "$input_1"|sed 's/[.]gz$//'`; input_1=`echo "$input_1"|sed 's/[.]gz$//'`; fi
if [ `echo "$input_2"|grep "[.]gz$"|wc -l||true` = 1 ]; then DO_BASE gzip -dc "$input_2" > `echo "$input_2"|sed 's/[.]gz$//'`; input_2=`echo "$input_2"|sed 's/[.]gz$//'`; fi

DO_FASTANI fastANI -t $N_CPU -q "$input_1" -r "$input_2" -o fastANI.`basename "$input_1"`.`basename "$input_2"`.txt --visualize $opt_a
DO_GENO Rscript /usr/local/FastANI/scripts/visualize.R "$input_1" "$input_2" fastANI.`basename "$input_1"`.`basename "$input_2"`.txt.visual

post_processing

#<option detail>
#<opt_a>
-r, --ref <value>
     reference genome (fasta/fastq)[.gz]
--rl, --refList <value>
     a file containing list of reference genome files, one genome per line
-q, --query <value>
     query genome (fasta/fastq)[.gz]
--ql, --queryList <value>
     a file containing list of query genome files, one genome per line
-k, --kmer <value>
     kmer size <= 16 [default : 16]
-t, --threads <value>
     thread count for parallel execution [default : 1]
--fragLen <value>
     fragment length [default : 3,000]
--minFraction <value>
     minimum fraction of genome that must be shared for trusting ANI. If
     reference and query genome size differ, smaller one among the two is
     considered. [default : 0.2]
--maxRatioDiff <value>
     maximum difference between (Total Ref. Length/Total Occ. Hashes) and (Total
     Ref. Length/Total No. Hashes). [default : 10.0]
--visualize
     output mappings for visualization, can be enabled for single genome to
     single genome comparison only [disabled by default]
--matrix
     also output ANI values as lower triangular matrix (format inspired from
     phylip). If enabled, you should expect an output file with .matrix
     extension [disabled by default]
-o, --output <value>
     output file name
-s, --sanityCheck
     run sanity check
-v, --version
     show version
#</opt_a>
#</option detail>
