#!/bin/bash

explanation='
convert from gff3 to gtf
'
inputdef='
input_1::reference gene model file (gff3):*.gff,*.gff3,*.gff.gz,*.gff3.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):64
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1#"

export IM_BASE="c2997108/centos7:1-trinity_2.8.5-kallisto_0.46.0-blast_2.9.0-trinotate-3.1.1-R_4-kegg_4"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail


#decompress input files
if [ `echo "$input_1"|grep "[.]gz$"|wc -l||true` = 1 ]; then
 DO_BASE gzip -dc "$input_1" > `echo "$input_1"|sed 's/[.]gz$//'`;
 input_1=`echo "$input_1"|sed 's/[.]gz$//'`;
fi

awk -F'\t' '{OFS="\t"; gsub(/%../,"_",$9); gsub(/[^0-9a-zA-Z_;=-]/,"_",$9); print $0}' "$input_1"|
 awk -F'\t' '{
  split($9,arr,";"); str=""; for(i=1;i<=length(arr);i++){if(arr[i]!~"^[_0-9]"){if(str==""){str=arr[i]}else{str=str";"arr[i]}}};
  $9=str; OFS="\t"; print $0
 }'|awk '{
  if($0!~"^#"){
   OFS="\t"; split($9,arr,";"); str="";
   for(i=1;i<=length(arr);i++){
    if(arr[i]~"^ID=" || arr[i]~"^Name=" || arr[i]~"^Note=" || arr[i]~"^Parent"){
     if(str==""){str=arr[i]}else{str=str";"arr[i]}
    }else{
     if(str==""){str=tolower(substr(arr[i],1,1))""substr(arr[i],2)}else{str=str";"tolower(substr(arr[i],1,1))""substr(arr[i],2)}
    }
   };
   $9=str
  };
  print $0
 }' > "$input_1.rename"
temp_1=`echo "$input_1"|sed 's/[.]\(gff\|gff3\)$/.gtf/'`
temp_2=`echo "$input_1"|sed 's/[.]\(gff\|gff3\)$/.withname.gtf/'`
DO_BASE gff3ToGenePred "$input_1.rename" /dev/stdout | DO_BASE genePredToGtf file stdin "$temp_1"
sed 's/ \+/ /g' "$temp_1"| awk -F'\t' '
 FILENAME==ARGV[1] && $3=="gene"{
  split($9,arr,";"); id=""; name=""; note=""; for(i in arr){
   if(tolower(substr(arr[i],1,3))=="id="){id=substr(arr[i],4)}
   else if(tolower(substr(arr[i],1,5))=="gene="){name=substr(arr[i],6)}
   else if(tolower(substr(arr[i],1,5))=="note="){note=substr(arr[i],6)}};
  if(id!="" && name!="" && note!=""){id2name[id]=name"_"note}
  else if(id!="" && name!="" && note==""){id2name[id]=name}
  else if(id!="" && name=="" && note!=""){id2name[id]=note}
 }
 FILENAME==ARGV[2]{
  a=$0; sub(/.*; gene_name "/,"",a); sub(/".*/,"",a);
  if(a!~"\t" && id2name[a]!=""){b=$0; c=$0; sub(/; gene_name ".*/,"; gene_name \"",b); sub(/.*; gene_name "[^"]*"/,"\"",c); print b""id2name[a]""c}else{print $0}
 }' "$input_1.rename" /dev/stdin > "$temp_2"


post_processing

#<option detail>
#</option detail>

