#!/bin/bash

explanation='
SELDLA: Scaffold Extender with Low Depth Linkage Analysis
'
inputdef='
input_1::reference genome file:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz
input_2::genotype vcf:*.vcf,*.vcf.gz
input_3::family information:*.txt
input_4:option:pre-cleaned vcf file:*_clean.txt
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):64
opt_b:SELDLA option:-p 0.03 -b 0.03 --NonZeroSampleRate=0.05 --NonZeroPhaseRate=0.1 -r 4000 --RateOfNotNASNP=0.001 --RateOfNotNALD=0.01 --ldseqnum 3 --noNewVcf
opt_d:SELDLA mode (crossbreed, haploid, duploid, selfpollination):haploid
opt_o:SELDLA output basename:seldla
opt_r:Upper limit of intersection frequency (%):5
'
runcmd="$0 -c #opt_c# -m #opt_m# -b #opt_b# -d #opt_d# -o #opt_o# -p #input_4# #input_1# #input_2# #input_3#"

export IM_SELDLA="c2997108/seldla:2.1.2_2"
export IM_BASE="c2997108/seldla:2.1.2_2"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

if [ "$opt_d" != "crossbreed" -a "$opt_d" != "haploid" -a "$opt_d" != "duploid" -a "$opt_d" != "selfpollination" ]; then echo "Please specify crossbreed, haploid, duploid, selfpollination for SELDLA mode"; post_processing ; fi
if [ `echo "$input_1"|grep "[.]gz$"|wc -l||true` = 1 ]; then DO_BASE gzip -dc "$input_1" > `echo "$input_1"|sed 's/[.]gz$//'`; input_1=`echo "$input_1"|sed 's/[.]gz$//'`; fi
if [ `echo "$input_2"|grep "[.]gz$"|wc -l||true` = 1 ]; then DO_BASE gzip -dc "$input_2" > `echo "$input_2"|sed 's/[.]gz$//'`; input_2=`echo "$input_2"|sed 's/[.]gz$//'`; fi
if [ "$input_4" = "" ]; then
 DO_SELDLA SELDLA --mode=$opt_d -o "$opt_o" $opt_b --fasta "$input_1" --vcf "$input_2" --family "$input_3"
 tempclean="${opt_o}_clean.txt"
else
 DO_SELDLA SELDLA --mode=$opt_d -o "$opt_o" $opt_b --fasta "$input_1" --vcf "$input_2" --family "$input_3" --precleaned "$input_4"
 tempclean="$input_4"
fi

numfam=0
rm -f "$input_3.rm"
for k in `seq 1 $(cat "$input_3"|wc -l)`; do
 if [ `awk -F'\t' 'NR=='$k'{print NF}' "$input_3"` -gt 2 ]; then
  numfam=`expr $numfam + 1`;
  i="${opt_o}"_split_$numfam.txt.ld.ph
  j="${opt_o}"_split_$numfam.txt.ld
  awk -F'\t' '
   function rev(x){if(x==0){return 1}else if(x==1){return 0}else{return x}}
   FILENAME==ARGV[1]{for(i=4;i<=NF;i++){ph[$1][i]=$i}}
   FILENAME==ARGV[2]{cntP=0; cntM=0; for(i=4;i<=NF;i++){if($i==ph[$2][i]){cntP++}else if($i==rev(ph[$2][i])){cntM++}};
    if(cntP>=cntM){print $0}else{ORS=""; print $1"\t"$2"\t"$3; for(i=4;i<=NF;i++){print "\t"rev($i)}; ORS="\n"; print ""}}
  ' $i $j|awk -F'\t' '
   NR==1{for(i=4;i<=NF;i++){name[i]=$i}}
   NR>1{if($2==old){for(i=4;i<=NF;i++){if($i!=-1 && oldph[i]!=-1){cntT[i]++; if($i!=oldph[i]){cntN[i]++}}}}else{for(i=4;i<=NF;i++){oldph[i]=$i}}; old=$2; for(i=4;i<=NF;i++){if($i!=-1){oldph[i]=$i}}}
   END{for(i=4;i<=NF;i++){print name[i]"\t"cntN[i]"\t"cntT[i]"\t"NR-1}}
  '|awk '{print $0,$2/$3*100}' > $j.cross
  cat $j.cross|awk '$NF<='$opt_r > $j.cross.single
  awk -F'\t' -v mode=$opt_d '
   FILENAME==ARGV[1]{a[$1]=1}
   FILENAME==ARGV[2] && FNR=='$k'{ORS="";
    if(mode=="haploid"||mode=="selfpollination"){print $1; for(i=2;i<=NF;i++){if(a[$i]==1){print "\t"$i}}}
    else{print $1"\t"$2; for(i=3;i<=NF;i++){if(a[$i]==1){print "\t"$i}}};
    ORS="\n"; print ""}
  ' $j.cross.single "$input_3" >> "$input_3.rm"
 fi
done
cat "$input_3.rm"|sed 's/\t/\n/g'|awk -F'\t' '
 FILENAME==ARGV[1]{a[$1]=1}
 FILENAME==ARGV[2]{if(FNR==1){ORS=""; for(i=11;i<=NF;i++){if(a[$i]==1){f[i]=1}}}; print $1; for(i=2;i<=NF;i++){if(i<=10||f[i]==1){print "\t"$i}}; print "\n"}
' /dev/stdin "$tempclean" > "$tempclean".single

#2nd SELDLA
DO_SELDLA SELDLA --mode=$opt_d -o "${opt_o}_rm_contamination" $opt_b --fasta "$input_1" --vcf "$input_2" --family "$input_3.rm" --precleaned "$tempclean".single


post_processing

#<option detail>
#<opt_b>
SELDLA ver2.1.2
      --DP=VALUE             DP_threshold at the cleanupVcf step [1]
      --GQ=VALUE             GQ_threshold at the cleanupVcf step [0]
      --NonZeroSampleRate=VALUE
                             exclude ambiquous SNP at the cleanupVcf step (0-1)
                               [0.3]
  -p, --hqsnp=VALUE          high quality SNP rate at the splitVcf step [0.3]
  -b, --bal=VALUE            0 / 1 balance at the splitVcf step [0.1]
      --NeedSort             If the input vcf file is not sorted, use this
                               option at the splitVcf step
      --nl=VALUE             near SNP match rate at the Snp2Ld step (0.5-1) [0.
                               9]
  -r=VALUE                   the region to merge near SNP at the Snp2Ld step (
                               bp) [10000]
      --RateOfNotNASNP=VALUE threshold of the ratio that is not NA with each
                               other when comparing SNP at the Snp2Ld step [0.2]
  -l, --clmatch=VALUE        cluster match rate at the Ld2Ph step [0.8]
      --cs=VALUE             cluster size at the Ld2Ph step [2]
  -v, --spmatch=VALUE        split match rate at the Ld2Ph step (0.5-1) [0.7]
      --ldnum=VALUE          the minimum number of same LD at the Ld2Ph step [1]
      --ldseqnum=VALUE       the minimum number of consecutive LDs at the Ld2Ph
                               step [1]
      --UseAllLDClusters     use all LD clusters at the Ld2Ph step
      --RateOfNotNALD=VALUE  threshold of the ratio that is not NA with each
                               other when comparing LD at the LD2Ph step [0.4]
      --RemoveLowQualityPhases=VALUE
                             remove low quality phases after the LD2Ph step (
                               yes/no) [no]
  -s, --exmatch=VALUE        extension match rate at the Chain step (0.5-1) [0.
                               7]
      --NonZeroPhaseRate=VALUE
                             exclude ambiquous Phase at the Chain step (0-1) [0.
                               3]
      --noNewVcf             no converted vcf output with new position
  -o, --output=VALUE         output prefix [seldla]
      --vcf=VALUE            input VCF file <required>
      --fasta=VALUE          input FASTA file <required>
      --family=VALUE         input family file <required>
      --precleaned=VALUE     pre-calculated cleaned vcf file (if this option is
                               used, input vcf is not used.)
      --mode=VALUE           analysis mode (crossbreed, haploid, duploid,
                               selfpollination) [crossbreed]
  -h, --help                 show help.

for RAD-seq:    --GQ=20 -r 100 --DP=5 --cs=3 --mode=duploid
for crossbreed: --GQ=0 -r 4000 --DP=1 --ldseqnum=3 --mode=crossbreed
for single-cell sperm: -p 0.03 -b 0.03 --NonZeroSampleRate=0.05 --NonZeroPhaseRate=0.1 -r 4000 --RateOfNotNASNP=0.001 --RateOfNotNALD=0.01 --ldseqnum 3 --noNewVcf --precleaned=single-cell.vcf_clean.txt --mode=haploid
#</opt_b>
#</option detail>

