#!/bin/bash

explanation='
metagenome analysis pipeline with a GenBank FASTA file
'
inputdef='
input_1:directory:FASTQ(.gz):*.fastq,*.fq,*.fastq.gz,*.fq.gz
input_2:directory:FAFSTA or BLAST database:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz,*.txt,*.nal,*.ndb,*.nhd,*.nhi,*.nhr,*.nin,*.nnd,*.nni,*.nog,*.nos,*.not,*.nsq,*.ntf,*.nto
input_3:option:ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz:*.accession2taxid.gz
input_4:option:ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz:taxdump.tar.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
opt_b:blast option:
opt_d:bit score threshold:100
opt_t:Score from top of BLAST hits used in LCA:0.95
opt_g:read number for normalization:10000
'
runcmd="$0 -c #opt_c# -m #opt_m# -b #opt_b# -d #opt_d# -t #opt_t# -g #opt_g# -a #input_3# -e #input_4# #input_1# #input_2#"

export IM_BLAST="c2997108/centos7:2-blast-taxid-2-KronaTools-2.7"
export IM_BASE="c2997108/centos6:4"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

input_3="${opt_a:-}"
input_4="${opt_e:-}"

nal=`find "$input_2"/ | grep "[.]nal$" |head -n 1 |sed 's/[.]nal$//' || true`
nhd=`find "$input_2"/ | grep "[.]nhd$" |head -n 1 |sed 's/[.]nhd$//' || true`
if [ "$nal" != "" ]; then
 input_2="$nal"
elif [ "$nhd" != "" ]; then
 input_2="$nhd"
else
 input_2=`find "$input_2"/ | grep -E "[.](fa|fasta|fsa|fna|txt)(|[.]gz)$" |head -n 1 || true`
 if [ `echo "$input_2"|grep "[.]gz$"|wc -l||true` = 1 ]; then
  DO_BASE gzip -dc "$input_2" > `basename "$input_2" .gz`
  input_2=`basename "$input_2" .gz`
 fi
 if [ `echo "$input_2"|grep -E "[.](fa|fasta|fsa|fna|txt)$"|wc -l||true` = 1 ]; then
  sed 's/\r//' "$input_2" > `basename "$input_2"`.mod.fasta
  input_2=`basename "$input_2"`.mod.fasta
  DO_BLAST makeblastdb -in "$input_2" -dbtype nucl -hash_index
 fi
fi

if [ "$input_4" != "" ]; then
 tar vxf "$input_4"
 cat names.dmp |awk -F'\t' '$7=="scientific name"{print $0}' > names.dmp.sname
 awk -F'\t' '
  FILENAME==ARGV[1]{parent[$1]=$3}
  FILENAME==ARGV[2]{name[$1]=$3}
  END{for(i in name){str=name[i]; key=parent[i]; while(1){if(key==1){str=name[key]";"str; break}; str=name[key]";"str; key=parent[key]}; print i"\t"str}}
 ' nodes.dmp names.dmp.sname > names.dmp.sname.path
fi

cat << 'EOS' > run-gz.sh
i=$1
bitscore="$2"
top="$3"
blastop="$5"
cpu="$4"
ref="/replaced/to/ref"

set -ex

echo "##count reads"
n0=`expr $(zcat $i|wc -l) / 4`

echo "##convert fastq to fasta"
j=${i%.*}.fasta
zcat $i|awk 'NR%4==1{print ">"substr($0,2)} NR%4==2{print $0}' > $j

echo "##blast"
blastn -db "$ref" -query $j -outfmt 6 -out $j.blast -num_threads $cpu
echo "blast status: " $?
rm $j

echo "##filtering"
cat $j.blast|awk -F'\t' '$12>'$bitscore'{if(a[$1]==1){if($12>=topbit*'$top'){print $0}}else{a[$1]=1; topbit=$12; print $0}}' > $j.blast.filtered

echo "##determine LCA"
if [ `echo "$j"|egrep "^/"|wc -l` = 1 ]; then
 j2="/"$j
elif [ `echo "$j"|egrep "^~"|wc -l` = 1 ]; then
 j2="/"`echo $j|sed 's%^~%'"$HOME"'%'`
else
 j2="./"$j
fi

gzip -dc /usr/local/ncbi/nucl_gb.accession2taxid.ac-id.gz|awk -F'\t' '
 FILENAME==ARGV[1]{split($2,arr,"."); flag[arr[1]]=1}
 FILENAME==ARGV[2]{if(flag[$1]==1){taxid[$1]=$2}else{delete flag[$1]}}
 FILENAME==ARGV[3]{name[$1]=$2}
 FILENAME==ARGV[4]{split($2,arr,"."); print name[taxid[arr[1]]]"\t"$0}
' $j.blast.filtered /dev/stdin /usr/local/ncbi/names.dmp.sname.path $j2.blast.filtered > $j.blast.filtered.name

awk -F'\t' '
function searchLCA(data,  i, j, res, res2, str, n, stopflag){
 for(i in data){
  if(n==0){n=split(i,res,";")}
  else{split(i,res2,";"); for(j in res){if(res[j]!=res2[j]){res[j]=""}}}
 }
 if(res[1]!=""){str=res[1]}else{str="unknown"; stopflag=1};
 for(i=2;i<=n;i++){if(stopflag==0 && res[i]!=""){str=str";"res[i]}else{stopflag=1}}
 return str;
}
{
 if($2!=old){if(old!=""){print searchLCA(data)"\t"oldstr}; delete data; data[$1]=1; old=$2; oldstr=$0}
 else{data[$1]=1}
}
END{if(length(data)>0){print searchLCA(data)"\t"oldstr}}
' $j.blast.filtered.name > $j.blast.filtered.name.lca

awk -F'\t' '{cnt[$1]++} END{PROCINFO["sorted_in"]="@val_num_desc"; for(i in cnt){print i"\t"cnt[i]}}' $j.blast.filtered.name.lca > $j.blast.filtered.name.lca.cnt
awk -F'\t' '{print $0}' $j.blast.filtered.name.lca.cnt > $j.blast.filtered.name.lca.cnt2
cnt=`awk -F'\t' '{a+=$2} END{if(a==""){a=0}; print a}' $j.blast.filtered.name.lca.cnt`
echo -e "No Hit\t"`expr $n0 - $cnt` >> $j.blast.filtered.name.lca.cnt2
awk -F'\t' '
{n=split($1,arr,";"); ORS="\t"; print $2; for(i=1;i<n;i++){print arr[i]}; ORS="\n"; print arr[n]}
' $j.blast.filtered.name.lca.cnt2 > $j.blast.filtered.name.lca.cnt3

echo "##krona"
/usr/local/KronaTools-2.7/scripts/ImportText.pl $j.blast.filtered.name.lca.cnt3 -o $i.html

EOS

sed -i 's%/replaced/to/ref%'"$input_2"'%' run-gz.sh
if [ "$input_3" != "" ]; then sed -i 's%/usr/local/ncbi/nucl_gb.accession2taxid.ac-id.gz%'"$input_3"'%; s/taxid\[$1\]=$2/taxid\[$1\]=$3/' run-gz.sh; fi
if [ "$input_4" != "" ]; then sed -i 's%/usr/local/ncbi/names.dmp.sname.path%names.dmp.sname.path%' run-gz.sh; fi
sed 's/zcat/cat/g' run-gz.sh > run.sh

(for i in `find $input_1/|egrep "[.]f(ast|)q$"||true`; do
 echo $ENV_BLAST bash run.sh $i "$opt_d" "$opt_t" $N_CPU "$opt_b"
done
for i in `find $input_1/|egrep "[.]f(ast|)q[.]gz$"||true`; do
 echo $ENV_BLAST bash run-gz.sh $i "$opt_d" "$opt_t" $N_CPU "$opt_b"
done)|DOPARALLEL

WAITPARALLEL

DO_BLAST /usr/local/KronaTools-2.7/scripts/ImportText.pl $input_1/*.cnt3 -o all.html

for i in $input_1/*.fasta.blast.filtered.name.lca.cnt2; do
 echo -e "id\t$(basename `echo $i|sed 's/.fasta.blast.filtered.name.lca.cnt2$//'`)" > $i.input
 cat $i >> $i.input
done
DO_BASE merge_table.pl -k $input_1/*.fasta.blast.filtered.name.lca.cnt2.input|sed 's/\t\t/\t0\t/g; s/\t\t/\t0\t/g; s/\t$/\t0/' > all.counts.txt
DO_BASE awk -F'\t' '
 FILENAME==ARGV[1]{if(FNR>1){for(i=2;i<=NF;i++){a[i]+=$i}}}
 FILENAME==ARGV[2]{if(FNR==1){OFS="\t"; for(i=2;i<=NF;i++){$i=$i" (counts per '$opt_g')"; if(a[i]==0){a[i]=1}}; print $0}
                   else{ORS=""; print $1;for(i=2;i<=NF;i++){print "\t"$i/a[i]*'$opt_g'}; print "\n"}}
' all.counts.txt ./all.counts.txt > all.counts.per.$opt_g.txt
DO_BASE java -Xmx1G -jar /usr/local/bin/excel2.jar all.counts.txt all.counts.xlsx
DO_BASE java -Xmx1G -jar /usr/local/bin/excel2.jar all.counts.per.$opt_g.txt all.counts.per.$opt_g.xlsx

post_processing
#<option detail>
#<opt_b>
USAGE
  blastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-perc_identity float_value] [-qcov_hsp_perc float_value]
    [-max_hsps int_value] [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-penalty penalty] [-reward reward] [-no_greedy]
    [-min_raw_gapped_score int_value] [-template_type type]
    [-template_length int_value] [-dust DUST_options]
    [-filtering_db filtering_database]
    [-window_masker_taxid window_masker_taxid]
    [-window_masker_db window_masker_db] [-soft_masking soft_masking]
    [-ungapped] [-culling_limit int_value] [-best_hit_overhang float_value]
    [-best_hit_score_edge float_value] [-window_size int_value]
    [-off_diagonal_range int_value] [-use_index boolean] [-index_name string]
    [-lcase_masking] [-query_loc range] [-strand strand] [-parse_deflines]
    [-outfmt format] [-show_gis] [-num_descriptions int_value]
    [-num_alignments int_value] [-line_length line_length] [-html]
    [-max_target_seqs num_sequences] [-num_threads int_value] [-remote]
    [-version]

#</opt_b>
#</option detail>

