#!/bin/bash

explanation='
Minimap mapping for single-end read.
'
inputdef='
input_1::FASTQ:*.fastq,*.fq,*.fastq.gz,*.fq.gz
input_2::FASTA:*.fa,*.fasta,*.fna
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
opt_f:minimap2 option:-x map-ont
'
runcmd="$0 -c #opt_c# -m #opt_m# -f #opt_f# #input_1# #input_2#"

export IM_MINIMAP2="quay.io/biocontainers/minimap2:2.16--h84994c4_0"
export IM_SAMTOOLS="quay.io/biocontainers/samtools:1.9--h10a08f8_12"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail



fq="$input_1"
ref="$input_2"
DO_MINIMAP2 minimap2 -t $N_CPU -a $opt_f "$ref" "$fq" | (DO_SAMTOOLS samtools sort -@ $N_CPU -o output.bam)
DO_SAMTOOLS samtools index output.bam
DO_SAMTOOLS samtools faidx "$ref"

post_processing
#<option detail>
#<opt_f>
Options:
  Indexing:
    -H           use homopolymer-compressed k-mer (preferrable for PacBio)
    -k INT       k-mer size (no larger than 28) [15]
    -w INT       minizer window size [10]
    -I NUM       split index for every ~NUM input bases [4G]
    -d FILE      dump index to FILE []
  Mapping:
    -f FLOAT     filter out top FLOAT fraction of repetitive minimizers [0.0002]
    -g NUM       stop chain enlongation if there are no minimizers in INT-bp [5000]
    -G NUM       max intron length (effective with -xsplice; changing -r) [200k]
    -F NUM       max fragment length (effective with -xsr or in the fragment mode) [800]
    -r NUM       bandwidth used in chaining and DP-based alignment [500]
    -n INT       minimal number of minimizers on a chain [3]
    -m INT       minimal chaining score (matching bases minus log gap penalty) [40]
    -X           skip self and dual mappings (for the all-vs-all mode)
    -p FLOAT     min secondary-to-primary score ratio [0.8]
    -N INT       retain at most INT secondary alignments [5]
  Alignment:
    -A INT       matching score [2]
    -B INT       mismatch penalty [4]
    -O INT[,INT] gap open penalty [4,24]
    -E INT[,INT] gap extension penalty; a k-long gap costs min{O1+k*E1,O2+k*E2} [2,1]
    -z INT[,INT] Z-drop score and inversion Z-drop score [400,200]
    -s INT       minimal peak DP alignment score [80]
    -u CHAR      how to find GT-AG. f:transcript strand, b:both strands, n:don't match GT-AG [n]
  Input/Output:
    -a           output in the SAM format (PAF by default)
    -Q           don't output base quality in SAM
    -L           write CIGAR with >65535 ops at the CG tag
    -R STR       SAM read group line in a format like '@RG\tID:foo\tSM:bar' []
    -c           output CIGAR in PAF
    --cs[=STR]   output the cs tag; STR is 'short' (if absent) or 'long' [none]
    --MD         output the MD tag
    --eqx        write =/X CIGAR operators
    -Y           use soft clipping for supplementary alignments
    -t INT       number of threads [3]
    -K NUM       minibatch size for mapping [500M]
    --version    show version number
  Preset:
    -x STR       preset (always applied before other options; see minimap2.1 for details) []
                 - map-pb/map-ont: PacBio/Nanopore vs reference mapping
                 - ava-pb/ava-ont: PacBio/Nanopore read overlap
                 - asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence
                 - splice: long-read spliced alignment
                 - sr: genomic short-read mapping

#</opt_f>
#</option detail>

