#!/bin/bash

explanation='
Calcurate N50 of contigs
'
inputdef='
input_1:directory:FASTA:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1#"

export IM_ABYSS="c2997108/ubuntu18:abyss"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail


cd "$input_1"
DO_ABYSS abyss-fac -s 1 `ls |egrep "(fa|fasta|fsa|fna)(|[.]gz)$"` > N50.txt


post_processing
#<option detail>
#</option detail>
