#!/bin/bash

explanation='
Create a graph of coverage and contig length to check the contamination of the assembled contig.
'
inputdef='
input_1::FASTA:*.fa,*.fasta
input_2:directory option:paired-end FASTQ(.gz):*.fastq,*.fq,*.fastq.gz,*.fq.gz
input_3:directory option:single-end FASTQ(.gz):*.fastq,*.fq,*.fastq.gz,*.fq.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1# #input_2# #input_3#"

export IM_SAMTOOLS="quay.io/biocontainers/samtools:1.9--h91753b0_3"
export IM_AWK="c2997108/centos6:2-bwa-0.7.17-r1198-dirty"
export IM_BWA="c2997108/centos6:2-bwa-0.7.17-r1198-dirty"
export IM_R="c2997108/centos6:2-bwa-0.7.17-r1198-dirty"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail


ref=$input_1
DO_BWA bwa index $ref
DO_SAMTOOLS samtools faidx $ref

(for i in `find $input_2/ |egrep '(_R1.*|_1)[.]f(ast|)q(|[.]gz)$' || true`; do
 if [ `echo $i|egrep "_1[.]f(ast|)q(|[.]gz)$"|wc -l||true` = 1 ]; then
  j=`echo $i|sed 's/_1[.]f\(ast\|\)q/_2.f\1q/'`;
 elif [ `echo $i|egrep "_R1"|wc -l||true` = 1 ]; then
  j=`echo $i|sed 's/_R1/_R2/'`;
 else
  j=none
 fi
 i2=`basename $i`
 if [ -e "$j" ]; then
  samplename=`basename $i|sed 's/_1[.]f.*//'|sed 's/_R1.*//'`;
  echo "$ENV_BWA bwa mem -t $N_CPU -M -R \'@RG\\\tID:$samplename\\\tSM:$samplename\\\tLB:library\' \'$ref\' \'$i\' \'$j\' > \'$i2.sam\'"
 else
  samplename=`basename $i|sed 's/[.]f\(ast\|\)q.*//'`;
  echo "$ENV_BWA bwa mem -t $N_CPU -M -R \'@RG\\\tID:$samplename\\\tSM:$samplename\\\tLB:library\' \'$ref\' \'$i\' > \'$i2.sam\'"
 fi
done
for i in `find $input_3/ |egrep '[.]f(ast|)q(|[.]gz)$' || true`; do
 i2=`basename $i`
 samplename=`basename $i|sed 's/[.]f\(ast\|\)q.*//'`;
 echo "$ENV_BWA bwa mem -t $N_CPU -M -R \'@RG\\\tID:$samplename\\\tSM:$samplename\\\tLB:library\' \'$ref\' \'$i\' > \'$i2.sam\'"
done
) | DOPARALLEL

WAITPARALLEL



outname=`basename $ref`
cat *.sam|grep -v "^@"|DO_AWK awk -F'\t' '{a=$6; gsub(/[0-9]+[^0-9M]/,"",a); split(a,arr,"M"); map=0; for(i in arr){map+=arr[i]}; b=$6; gsub(/[^0-9]/,",",b); split(b,arr,","); total=0; for(i in arr){total+=arr[i]}; for(i=12;i<=NF;i++){if($i~"^MD:Z:"){c=$i; gsub(/^MD:Z:/,"",c); gsub(/[0-9]/,"",c); if((map-length(c))/total>=0.8){print map"\t"$0}}}}' > $outname.sam2
DO_AWK awk -F'\t' 'FILENAME==ARGV[1]{len[$1]=$2} FILENAME==ARGV[2]{a[$4]+=$1} END{for(i in a){print i"\t"a[i]/len[i]"\t"a[i]"\t"len[i]}}' $ref.fai $outname.sam2 > $outname.sam2.cov
echo 'library(Cairo); a=read.table("'$outname.sam2.cov'",sep="\t",row.names=1); CairoPNG(file="'$outname.sam2.cov'.png",width=1000,height=1000); sunflowerplot(x=a[,1], y=a[,3], xlab="coverage [fold]", ylab="contig length [bp]", log="xy"); dev.off()' | DO_R R --vanilla < /dev/stdin
(DO_SAMTOOLS samtools view -SH `ls -S *.sam|head -n 1`; cut -f 2- $outname.sam2)|DO_SAMTOOLS samtools view -Sb -@ $N_CPU - | DO_SAMTOOLS samtools sort -T $outname.clean -@ $N_CPU -o $outname.clean.bam
(echo -e 'id\tcoverage\tmapped bases\tlength'; cat $outname.sam2.cov) > $outname.output.txt

rm -f *.sam $outname.sam2
DO_SAMTOOLS samtools index $outname.clean.bam


post_processing
#<option detail>
#</option detail>
