#!/bin/bash

explanation='
A quality control tool for high throughput sequence data.
'
inputdef='
input_1:directory:FASTQ(.gz):*.fastq,*.fq,*.fastq.gz,*.fq.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1#"

export IM_FASTQC="quay.io/biocontainers/fastqc:0.11.8--1"

source $(dirname `readlink -f $0`)/common.sh

set -eux

cd $input_1

for i in `ls |egrep "[.](fq|fastq|fq.gz|fastq.gz)$"`; do echo $ENV_FASTQC fastqc -t 1 $i --extract; done|xargs -I{} -P$N_CPU bash -c "{}"

echo "<html><head></head><body><table><tr><td>name</td>" > index.html

for i in *_fastqc; do
 echo "<td>"$i"</td>" >> index.html
done

echo "</tr>" >> index.html

file0=`ls -d *_fastqc|head -n 1`
for j in `seq 5 10`; do
echo "<tr><td>"`head -n $j $file0/fastqc_data.txt|tail -n 1 |cut -f 1`"</td>" >> index.html
for i in *_fastqc; do
 echo "<td>"`head -n $j $i/fastqc_data.txt|tail -n 1 |cut -f 2`"</td>" >> index.html
done
echo "</tr>" >> index.html
done

echo "<tr><td>Overrepresented sequences</td>" >> index.html
for i in *_fastqc; do
 echo "<td><pre>" >> index.html
 tail -n+`grep -n Overrepresented $i/fastqc_data.txt|cut -f 1 -d ':'` $i/fastqc_data.txt > temp.txt
 head -n `grep -n ">>END_MODULE" temp.txt|head -n 1|cut -f 1 -d ':'` temp.txt|tail -n+3|head -n-1 >> index.html
 echo "</td></pre>" >> index.html
done
echo "</tr>" >> index.html

for j in per_base_quality.png per_tile_quality.png per_sequence_gc_content.png adapter_content.png duplication_levels.png kmer_profiles.png per_base_n_content.png per_base_sequence_content.png per_sequence_quality.png sequence_length_distribution.png; do
echo "<tr><td>$j</td>" >> index.html
for i in *_fastqc; do
 echo "<td><a href='$i/Images/$j'><img width='200' src='$i/Images/$j'></a></td>" >> index.html
done
echo "</tr>" >> index.html
done

echo "</table></body></html>" >> index.html

rm -f temp.txt

post_processing
#<option detail>
#<opt_c>
#</opt_c>
#</option detail>
