#!/bin/bash

explanation='
genotyping by bcftools mpileup
This pipeline is intended to analyze more than 100 samples and execute jobs in parallel.
'
inputdef='
input_1:directory:paired-end FASTQ(.gz) files:*.fastq,*.fq,*.fastq.gz,*.fq.gz
input_2::reference genome file:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz
'
optiondef='
opt_c:cpu threads:4
opt_m:memory limit (GB):32
opt_b:bwa mem option:
opt_g:bcftools mpileup option:--annotate AD,DP,INFO/AD
opt_i:bcftools call option:-vm -f GQ
'
runcmd="$0 -c #opt_c# -m #opt_m# -b #opt_b# -g #opt_g# -i #opt_i# #input_1# #input_2#"

export IM_BASE="c2997108/centos7:1-trinity_2.8.5-kallisto_0.46.0-blast_2.9.0-trinotate-3.1.1-R_4-kegg_4"
export IM_BWA="quay.io/biocontainers/bwa:0.7.17--pl5.22.0_1"
export IM_SAMTOOLS="biocontainers/samtools:v1.7.0_cv4"
export IM_BCF="quay.io/biocontainers/bcftools:1.9--h68d8f2e_7"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail


if [ `echo "$input_2"|grep "[.]gz$"|wc -l||true` = 1 ]; then DO_BASE gzip -dc "$input_2" > `echo "$input_2"|sed 's/[.]gz$//'`; input_2=`echo "$input_2"|sed 's/[.]gz$//'`; fi
ref="$input_2"
DO_SAMTOOLS samtools faidx "$ref"
DO_BWA bwa index "$ref"

mkdir -p output.bwa
for i in `find $input_1/ |egrep '(_R1.*|_1)[.]f(ast|)q(|[.]gz)$'`; do
 if [ `echo $i|egrep "_1[.]f(ast|)q(|[.]gz)$"|wc -l||true` = 1 ]; then
  i2=`echo $i|sed 's/_1[.]f\(ast\|\)q/_2.f\1q/'`;
 else
  i2=`echo $i|sed 's/_R1/_R2/'`;
 fi
 outbase=output.bwa/`basename $i|sed 's/_1[.]f.*//'|sed 's/_R1.*//'`;
 samplename=`basename $i|sed 's/_1[.]f.*//'|sed 's/_R1.*//'`;
 echo "$ENV_BWA bwa mem $opt_b -t $N_CPU -R \'@RG\\\tID:$samplename\\\tSM:$samplename\\\tLB:library\' \'$ref\' \'$i\' \'$i2\' |( $ENV_SAMTOOLS samtools sort -@ $N_CPU -o \'$outbase\'.bam); $ENV_SAMTOOLS samtools index \'$outbase\'.bam"
done | DOPARALLEL

WAITPARALLEL

mkdir -p output.mpileup

awk -F'\t' '{for(i=1;i<int($2/1000/1000)+1;i++){print $1":"1+(i-1)*1000*1000"-"i*1000*1000"\t"1000*1000}; print $1":"1+(i-1)*1000*1000"-"$2"\t"$2-1+(i-1)*1000*1000}' "$ref".fai |awk -F'\t' '{cnt+=$2; if(str==""){str=$1}else{str=str","$1}; if(cnt>=1000*1000){print str; str=""; cnt=0}} END{if(str!=""){print str}}' > temp.region.list
n=`cat temp.region.list|wc -l`

cat << EOF > run-mpileup-split.sh
#!/bin/bash
j=\$1
i=\`head -n \$j temp.region.list|tail -n 1\`
bcftools mpileup -Ou $opt_g -r "\$i" -f "${ref}" output.bwa/*.bam | bcftools call $opt_i -o output.mpileup/out.\$j.vcf
EOF

j=0
for i in `seq 1 $n`; do
 j=`expr $j + 1`
# echo "$ENV_BCF bcftools mpileup -Ou $opt_g -r \'$i\' -f \'${ref}\' output.bwa/*.bam \|( $ENV_BCF bcftools call $opt_i -o output.mpileup/out.\'$j\'.vcf)"
 echo "$ENV_BCF bash run-mpileup-split.sh $j"
done | DOPARALLEL

WAITPARALLEL

(DO_BASE cat output.mpileup/out.1.vcf;
 for i in `ls output.mpileup/out.*.vcf|grep -v output.mpileup/out.1.vcf|sort -V`; do DO_BASE cat $i|grep -v "^#" ||true; done
) > all.vcf


post_processing

#<option detail>
#<opt_b>
Algorithm options:

       -t INT        number of threads [1]
       -k INT        minimum seed length [19]
       -w INT        band width for banded alignment [100]
       -d INT        off-diagonal X-dropoff [100]
       -r FLOAT      look for internal seeds inside a seed longer than {-k} * FLOAT [1.5]
       -y INT        seed occurrence for the 3rd round seeding [20]
       -c INT        skip seeds with more than INT occurrences [500]
       -D FLOAT      drop chains shorter than FLOAT fraction of the longest overlapping chain [0.50]
       -W INT        discard a chain if seeded bases shorter than INT [0]
       -m INT        perform at most INT rounds of mate rescues for each read [50]
       -S            skip mate rescue
       -P            skip pairing; mate rescue performed unless -S also in use

Scoring options:

       -A INT        score for a sequence match, which scales options -TdBOELU unless overridden [1]
       -B INT        penalty for a mismatch [4]
       -O INT[,INT]  gap open penalties for deletions and insertions [6,6]
       -E INT[,INT]  gap extension penalty; a gap of size k cost '{-O} + {-E}*k' [1,1]
       -L INT[,INT]  penalty for 5'- and 3'-end clipping [5,5]
       -U INT        penalty for an unpaired read pair [17]

       -x STR        read type. Setting -x changes multiple parameters unless overriden [null]
                     pacbio: -k17 -W40 -r10 -A1 -B1 -O1 -E1 -L0  (PacBio reads to ref)
                     ont2d: -k14 -W20 -r10 -A1 -B1 -O1 -E1 -L0  (Oxford Nanopore 2D-reads to ref)
                     intractg: -B9 -O16 -L5  (intra-species contigs to ref)
#</opt_b>
#<opt_g>
Usage: bcftools mpileup [options] in1.bam [in2.bam [...]]

Input options:
  -6, --illumina1.3+      quality is in the Illumina-1.3+ encoding
  -A, --count-orphans     do not discard anomalous read pairs
  -b, --bam-list FILE     list of input BAM filenames, one per line
  -B, --no-BAQ            disable BAQ (per-Base Alignment Quality)
  -C, --adjust-MQ INT     adjust mapping quality; recommended:50, disable:0 [0]
  -d, --max-depth INT     max per-file depth; avoids excessive memory usage [250]
  -E, --redo-BAQ          recalculate BAQ on the fly, ignore existing BQs
  -f, --fasta-ref FILE    faidx indexed reference sequence file
      --no-reference      do not require fasta reference file
  -G, --read-groups FILE  select or exclude read groups listed in the file
  -q, --min-MQ INT        skip alignments with mapQ smaller than INT [0]
  -Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]
  -r, --regions REG[,...] comma separated list of regions in which pileup is generated
  -R, --regions-file FILE restrict to regions listed in a file
      --ignore-RG         ignore RG tags (one BAM = one sample)
  --rf, --incl-flags STR|INT  required flags: skip reads with mask bits unset []
  --ff, --excl-flags STR|INT  filter flags: skip reads with mask bits set
                                            [UNMAP,SECONDARY,QCFAIL,DUP]
  -s, --samples LIST      comma separated list of samples to include
  -S, --samples-file FILE file of samples to include
  -t, --targets REG[,...] similar to -r but streams rather than index-jumps
  -T, --targets-file FILE similar to -R but streams rather than index-jumps
  -x, --ignore-overlaps   disable read-pair overlap detection

Output options:
  -a, --annotate LIST     optional tags to output; '?' to list []
  -g, --gvcf INT[,...]    group non-variant sites into gVCF blocks according
                          to minimum per-sample DP
      --no-version        do not append version and command line to the header
  -o, --output FILE       write output to FILE [standard output]
  -O, --output-type TYPE  'b' compressed BCF; 'u' uncompressed BCF;
                          'z' compressed VCF; 'v' uncompressed VCF [v]
      --threads INT       number of extra output compression threads [0]

SNP/INDEL genotype likelihoods options:
  -e, --ext-prob INT      Phred-scaled gap extension seq error probability [20]
  -F, --gap-frac FLOAT    minimum fraction of gapped reads [0.002]
  -h, --tandem-qual INT   coefficient for homopolymer errors [100]
  -I, --skip-indels       do not perform indel calling
  -L, --max-idepth INT    maximum per-file depth for INDEL calling [250]
  -m, --min-ireads INT    minimum number gapped reads for indel candidates [1]
  -o, --open-prob INT     Phred-scaled gap open seq error probability [40]
  -p, --per-sample-mF     apply -m and -F per-sample for increased sensitivity
  -P, --platforms STR     comma separated list of platforms for indels [all]

Notes: Assuming diploid individuals.
#</opt_g>
#<opt_i>
About:   SNP/indel variant calling from VCF/BCF. To be used in conjunction with samtools mpileup.
         This command replaces the former "bcftools view" caller. Some of the original
         functionality has been temporarily lost in the process of transition to htslib,
         but will be added back on popular demand. The original calling model can be
         invoked with the -c option.
Usage:   bcftools call [options] <in.vcf.gz>

File format options:
       --no-version                do not append version and command line to the header
   -o, --output <file>             write output to a file [standard output]
   -O, --output-type <b|u|z|v>     output type: 'b' compressed BCF; 'u' uncompressed BCF; 'z' compressed VCF; 'v' uncompressed VCF [v]
       --ploidy <assembly>[?]      predefined ploidy, 'list' to print available settings, append '?' for details
       --ploidy-file <file>        space/tab-delimited list of CHROM,FROM,TO,SEX,PLOIDY
   -r, --regions <region>          restrict to comma-separated list of regions
   -R, --regions-file <file>       restrict to regions listed in a file
   -s, --samples <list>            list of samples to include [all samples]
   -S, --samples-file <file>       PED file or a file with an optional column with sex (see man page for details) [all samples]
   -t, --targets <region>          similar to -r but streams rather than index-jumps
   -T, --targets-file <file>       similar to -R but streams rather than index-jumps
       --threads <int>             number of extra output compression threads [0]

Input/output options:
   -A, --keep-alts                 keep all possible alternate alleles at variant sites
   -f, --format-fields <list>      output format fields: GQ,GP (lowercase allowed) []
   -F, --prior-freqs <AN,AC>       use prior allele frequencies
   -g, --gvcf <int>,[...]          group non-variant sites into gVCF blocks by minimum per-sample DP
   -i, --insert-missed             output also sites missed by mpileup but present in -T
   -M, --keep-masked-ref           keep sites with masked reference allele (REF=N)
   -V, --skip-variants <type>      skip indels/snps
   -v, --variants-only             output variant sites only

Consensus/variant calling options:
   -c, --consensus-caller          the original calling method (conflicts with -m)
   -C, --constrain <str>           one of: alleles, trio (see manual)
   -m, --multiallelic-caller       alternative model for multiallelic and rare-variant calling (conflicts with -c)
   -n, --novel-rate <float>,[...]  likelihood of novel mutation for constrained trio calling, see man page for details [1e-8,1e-9,1e-9]
   -p, --pval-threshold <float>    variant if P(ref|D)<FLOAT with -c [0.5]
   -P, --prior <float>             mutation rate (use bigger for greater sensitivity), use with -m [1.1e-3]
#</opt_i>
#</option detail>

