#!/bin/bash

explanation='
genotyping by GATK
This pipeline is intended to analyze more than 100 samples and execute jobs in parallel.
'
inputdef='
input_1:directory:paired-end FASTQ(.gz) files:*.fastq,*.fq,*.fastq.gz,*.fq.gz
input_2::reference genome file:*.fa,*.fasta,*.fsa,*.fna,*.fa.gz,*.fasta.gz,*.fsa.gz,*.fna.gz
'
optiondef='
opt_c:cpu threads:4
opt_m:memory limit (GB):32
opt_b:bwa mem option:
opt_g:GATK GenotypeGVCFs option:
'
runcmd="$0 -c #opt_c# -m #opt_m# -b #opt_b# -g #opt_g# #input_1# #input_2#"

export IM_PICARD="quay.io/biocontainers/picard:2.18.27--0"
export IM_BASE="c2997108/centos7:1-trinity_2.8.5-kallisto_0.46.0-blast_2.9.0-trinotate-3.1.1-R_4-kegg_4"
export IM_BWA="quay.io/biocontainers/bwa:0.7.17--pl5.22.0_1"
export IM_SAMTOOLS="biocontainers/samtools:v1.7.0_cv4"
export IM_GATK="quay.io/biocontainers/gatk4:4.1.0.0--0"
export IM_TRINITY="quay.io/biocontainers/trinity:2.8.4--py36pl526h447964c_0"
export IM_EXONERATE="quay.io/biocontainers/exonerate:2.2.0--1"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail


if [ `echo "$input_2"|grep "[.]gz$"|wc -l||true` = 1 ]; then DO_BASE gzip -dc "$input_2" > `echo "$input_2"|sed 's/[.]gz$//'`; input_2=`echo "$input_2"|sed 's/[.]gz$//'`; fi
refbase=`echo "$input_2"|sed 's/[.]\(fa\|fasta\|fsa\|fna\)$//'`
if [ -e "$refbase".dict ]; then DO_PICARD rm -f "$refbase".dict; fi
DO_PICARD picard CreateSequenceDictionary R="$input_2" O="$refbase".dict
DO_SAMTOOLS samtools faidx "$input_2"

DO_TRINITY /usr/local/opt/trinity-2.8.4/util/support_scripts/fasta_to_tab.pl "$input_2" > "$input_2".tab
awk '{print length($NF)"\t"$1"\t"$NF}' "$input_2".tab |sort -nr|awk '{if($1>1000*1000){print ">"$2; print $3; print $2"\t"$2"\t1\t"$1 > "pseudochr.txt"}else{if(n==0 || n>10*1000*1000){m++; n=1; print ">pseudochr"m}else{n+=200*50; for(i=0;i<200;i++){print "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"}}; print $3; print $2"\tpseudochr"m"\t"n"\t"n+$1-1 > "pseudochr.txt"; n+=$1}}' > pseudochr.fa
cat pseudochr.txt |awk '{print $2"\t"$3-1"\t"$4"\t"$1"\t0\t+"}' > pseudochr.bed
DO_EXONERATE fastareformat pseudochr.fa > pseudochr.re.fa
rm -f pseudochr.fa
DO_SAMTOOLS samtools faidx pseudochr.re.fa
DO_BWA bwa index pseudochr.re.fa
if [ -e pseudochr.re.dict ]; then DO_PICARD rm -f pseudochr.re.dict; fi
DO_PICARD picard CreateSequenceDictionary R=pseudochr.re.fa O=pseudochr.re.dict

ref=pseudochr.re.fa
MEMG=`echo ${N_MEM}|awk -v N_CPU=$N_CPU '{print int($1/1024/1024/N_CPU*0.8)}'`
mkdir -p output.bwa
for i in `find $input_1/ |egrep '(_R1.*|_1)[.]f(ast|)q(|[.]gz)$'`; do
 if [ `echo $i|egrep "_1[.]f(ast|)q(|[.]gz)$"|wc -l||true` = 1 ]; then
  i2=`echo $i|sed 's/_1[.]f\(ast\|\)q/_2.f\1q/'`;
 else
  i2=`echo $i|sed 's/_R1/_R2/'`;
 fi
 outbase=output.bwa/`basename $i|sed 's/_1[.]f.*//'|sed 's/_R1.*//'`;
 samplename=`basename $i|sed 's/_1[.]f.*//'|sed 's/_R1.*//'`;
 echo "$ENV_BWA bwa mem $opt_b -t $N_CPU -R '@RG\tID:$samplename\tSM:$samplename\tLB:library' '$ref' '$i' '$i2' |( $ENV_SAMTOOLS samtools sort -@ $N_CPU -o '$outbase'.bam); $ENV_SAMTOOLS samtools index '$outbase'.bam; $ENV_GATK gatk --java-options '-Xmx${N_MEM_G}g -XX:ParallelGCThreads=1' HaplotypeCaller -R '$ref' -I '$outbase'.bam -O '$outbase'.g.vcf.gz -ERC GVCF"
done | DOPARALLEL

WAITPARALLEL

ls output.bwa/*.g.vcf.gz > gvcf.list.txt
cat gvcf.list.txt |sed 's%output.bwa/%%; s/.g.vcf.gz//' > gvcf.list.txt2
paste gvcf.list.txt2 gvcf.list.txt > gvcf.list.txt3
mkdir -p output.gatk
for i in `cat $ref.fai |cut -f 1`; do
 if [ -e output.gatk/genomicsdb.$i ]; then DO_GATK rm -rf output.gatk/genomicsdb.$i; fi
 echo "$ENV_GATK gatk --java-options '-Xmx${N_MEM_G}g -XX:ParallelGCThreads=1' GenomicsDBImport --genomicsdb-workspace-path output.gatk/genomicsdb.$i --batch-size 5 -L $i --sample-name-map gvcf.list.txt3 --reader-threads 1; $ENV_GATK gatk --java-options '-Xmx${N_MEM_G}g -XX:ParallelGCThreads=1' GenotypeGVCFs $opt_g -R $ref -O output.gatk/out.$i.vcf.gz -V gendb://output.gatk/genomicsdb.$i -L $i"
done | DOPARALLEL

WAITPARALLEL

DO_GATK rm -rf output.gatk/genomicsdb.*

(DO_BASE zcat output.gatk/out.`head -n 1 pseudochr.re.fa.fai |cut -f 1`.vcf.gz|grep "^##"|grep -v "^##contig=<ID=";
 awk -F'\t' 'FILENAME==ARGV[1]{len[$1]=$2} FILENAME==ARGV[2]{print "##contig=<ID="$1",length="len[$1]">"}' "$input_2".fai pseudochr.txt;
 (DO_BASE zcat output.gatk/out.`head -n 1 pseudochr.re.fa.fai |cut -f 1`.vcf.gz;
  for i in `tail -n+2 pseudochr.re.fa.fai |cut -f 1`; do DO_BASE zcat output.gatk/out.$i.vcf.gz|grep -v "^#" ||true; done
 )|grep -v "^##" |awk -F'\t' '
    FILENAME==ARGV[1]{chr0[NR]=$1; chr1[NR]=$2; poss[NR]=$3; pose[NR]=$4; n=NR; m=1}
    FILENAME==ARGV[2]{if(FNR==1){print $0}else{for(i=m;i<=n;i++){m=i; if(chr1[i]==$1 && poss[i]<=$2 && pose[i]>=$2){f=1; break}}; if(f==1){$1=chr0[m]; $2=$2-poss[m]+1; OFS="\t"; print $0; f=0}}}
   ' pseudochr.txt /dev/stdin
) > all.re.vcf


post_processing

#<option detail>
#<opt_b>
Algorithm options:

       -t INT        number of threads [1]
       -k INT        minimum seed length [19]
       -w INT        band width for banded alignment [100]
       -d INT        off-diagonal X-dropoff [100]
       -r FLOAT      look for internal seeds inside a seed longer than {-k} * FLOAT [1.5]
       -y INT        seed occurrence for the 3rd round seeding [20]
       -c INT        skip seeds with more than INT occurrences [500]
       -D FLOAT      drop chains shorter than FLOAT fraction of the longest overlapping chain [0.50]
       -W INT        discard a chain if seeded bases shorter than INT [0]
       -m INT        perform at most INT rounds of mate rescues for each read [50]
       -S            skip mate rescue
       -P            skip pairing; mate rescue performed unless -S also in use

Scoring options:

       -A INT        score for a sequence match, which scales options -TdBOELU unless overridden [1]
       -B INT        penalty for a mismatch [4]
       -O INT[,INT]  gap open penalties for deletions and insertions [6,6]
       -E INT[,INT]  gap extension penalty; a gap of size k cost '{-O} + {-E}*k' [1,1]
       -L INT[,INT]  penalty for 5'- and 3'-end clipping [5,5]
       -U INT        penalty for an unpaired read pair [17]

       -x STR        read type. Setting -x changes multiple parameters unless overriden [null]
                     pacbio: -k17 -W40 -r10 -A1 -B1 -O1 -E1 -L0  (PacBio reads to ref)
                     ont2d: -k14 -W20 -r10 -A1 -B1 -O1 -E1 -L0  (Oxford Nanopore 2D-reads to ref)
                     intractg: -B9 -O16 -L5  (intra-species contigs to ref)
#</opt_b>
#<opt_g>
Optional Arguments:

--add-output-sam-program-record,-add-output-sam-program-record:Boolean
                              If true, adds a PG tag to created SAM/BAM/CRAM files.  Default value: true. Possible
                              values: {true, false}

--add-output-vcf-command-line,-add-output-vcf-command-line:Boolean
                              If true, adds a command line header line to created VCF files.  Default value: true.
                              Possible values: {true, false}

--allele-fraction-error:DoubleMargin of error in allele fraction to consider a somatic variant homoplasmic  Default
                              value: 0.001.

--annotate-with-num-discovered-alleles:Boolean
                              If provided, we will annotate records with the number of alternate alleles that were
                              discovered (but not necessarily genotyped) at a given site  Default value: false. Possible
                              values: {true, false}

--annotation,-A:String        One or more specific annotations to add to variant calls  This argument may be specified 0
                              or more times. Default value: null. Possible Values: {AlleleFraction,
                              AS_BaseQualityRankSumTest, AS_FisherStrand, AS_InbreedingCoeff,
                              AS_MappingQualityRankSumTest, AS_QualByDepth, AS_ReadPosRankSumTest, AS_RMSMappingQuality,
                              AS_StrandOddsRatio, BaseQuality, BaseQualityRankSumTest, ChromosomeCounts,
                              ClippingRankSumTest, CountNs, Coverage, DepthPerAlleleBySample, DepthPerSampleHC,
                              ExcessHet, FisherStrand, FragmentLength, GenotypeSummaries, InbreedingCoeff,
                              LikelihoodRankSumTest, MappingQuality, MappingQualityRankSumTest, MappingQualityZero,
                              OrientationBiasReadCounts, OriginalAlignment, PossibleDeNovo, QualByDepth, ReadPosition,
                              ReadPosRankSumTest, ReferenceBases, RMSMappingQuality, SampleList, StrandBiasBySample,
                              StrandOddsRatio, TandemRepeat, UniqueAltReadCount}

--annotation-group,-G:String  One or more groups of annotations to apply to variant calls  This argument may be
                              specified 0 or more times. Default value: null. Possible Values: {AS_StandardAnnotation,
                              ReducibleAnnotation, StandardAnnotation, StandardHCAnnotation, StandardMutectAnnotation}

--annotations-to-exclude,-AX:String
                              One or more specific annotations to exclude from variant calls  This argument may be
                              specified 0 or more times. Default value: null. Possible Values: {BaseQualityRankSumTest,
                              ChromosomeCounts, Coverage, DepthPerAlleleBySample, ExcessHet, FisherStrand,
                              InbreedingCoeff, MappingQualityRankSumTest, QualByDepth, ReadPosRankSumTest,
                              RMSMappingQuality, StrandOddsRatio}

--arguments_file:File         read one or more arguments files and add them to the command line  This argument may be
                              specified 0 or more times. Default value: null.

--cloud-index-prefetch-buffer,-CIPB:Integer
                              Size of the cloud-only prefetch buffer (in MB; 0 to disable). Defaults to
                              cloudPrefetchBuffer if unset.  Default value: -1.

--cloud-prefetch-buffer,-CPB:Integer
                              Size of the cloud-only prefetch buffer (in MB; 0 to disable).  Default value: 40.

--create-output-bam-index,-OBI:Boolean
                              If true, create a BAM/CRAM index when writing a coordinate-sorted BAM/CRAM file.  Default
                              value: true. Possible values: {true, false}

--create-output-bam-md5,-OBM:Boolean
                              If true, create a MD5 digest for any BAM/SAM/CRAM file created  Default value: false.
                              Possible values: {true, false}

--create-output-variant-index,-OVI:Boolean
                              If true, create a VCF index when writing a coordinate-sorted VCF file.  Default value:
                              true. Possible values: {true, false}

--create-output-variant-md5,-OVM:Boolean
                              If true, create a a MD5 digest any VCF file created.  Default value: false. Possible
                              values: {true, false}

--dbsnp,-D:FeatureInput       dbSNP file  Default value: null.

--disable-bam-index-caching,-DBIC:Boolean
                              If true, don't cache bam indexes, this will reduce memory requirements but may harm
                              performance if many intervals are specified.  Caching is automatically disabled if there
                              are no intervals specified.  Default value: false. Possible values: {true, false}

--disable-read-filter,-DF:String
                              Read filters to be disabled before analysis  This argument may be specified 0 or more
                              times. Default value: null. Possible Values: {WellformedReadFilter}

--disable-sequence-dictionary-validation,-disable-sequence-dictionary-validation:Boolean
                              If specified, do not check the sequence dictionaries from our inputs for compatibility.
                              Use at your own risk!  Default value: false. Possible values: {true, false}

--exclude-intervals,-XL:StringOne or more genomic intervals to exclude from processing  This argument may be specified 0
                              or more times. Default value: null.

--founder-id,-founder-id:String
                              Samples representing the population "founders"  This argument may be specified 0 or more
                              times. Default value: null.

--gatk-config-file:String     A configuration file to use with the GATK.  Default value: null.

--gcs-max-retries,-gcs-retries:Integer
                              If the GCS bucket channel errors out, how many times it will attempt to re-initiate the
                              connection  Default value: 20.

--gcs-project-for-requester-pays:String
                              Project to bill when accessing "requester pays" buckets. If unset, these buckets cannot be
                              accessed.  Default value: .

--help,-h:Boolean             display the help message  Default value: false. Possible values: {true, false}

--heterozygosity:Double       Heterozygosity value used to compute prior likelihoods for any locus.  See the GATKDocs
                              for full details on the meaning of this population genetics concept  Default value: 0.001.

--heterozygosity-stdev:Double Standard deviation of heterozygosity for SNP and indel calling.  Default value: 0.01.

--include-non-variant-sites,-all-sites:Boolean
                              Include loci found to be non-variant after genotyping  Default value: false. Possible
                              values: {true, false}

--indel-heterozygosity:Double Heterozygosity for indel calling.  See the GATKDocs for heterozygosity for full details on
                              the meaning of this population genetics concept  Default value: 1.25E-4.

--input,-I:String             BAM/SAM/CRAM file containing reads  This argument may be specified 0 or more times.
                              Default value: null.

--input-is-somatic:Boolean    Finalize input GVCF according to somatic (i.e. Mutect2) TLODs (BETA feature)  Default
                              value: false. Possible values: {true, false}

--interval-exclusion-padding,-ixp:Integer
                              Amount of padding (in bp) to add to each interval you are excluding.  Default value: 0.

--interval-merging-rule,-imr:IntervalMergingRule
                              Interval merging rule for abutting intervals  Default value: ALL. Possible values: {ALL,
                              OVERLAPPING_ONLY}

--interval-padding,-ip:IntegerAmount of padding (in bp) to add to each interval you are including.  Default value: 0.

--interval-set-rule,-isr:IntervalSetRule
                              Set merging approach to use for combining interval inputs  Default value: UNION. Possible
                              values: {UNION, INTERSECTION}

--intervals,-L:String         One or more genomic intervals over which to operate  This argument may be specified 0 or
                              more times. Default value: null.

--keep-combined-raw-annotations,-keep-combined:Boolean
                              If specified, keep the combined raw annotations  Default value: false. Possible values:
                              {true, false}

--lenient,-LE:Boolean         Lenient processing of VCF files  Default value: false. Possible values: {true, false}

--merge-input-intervals,-merge-input-intervals:Boolean
                              Boolean flag to import all data in between intervals.  Default value: false. Possible
                              values: {true, false}

--num-reference-samples-if-no-call:Integer
                              Number of hom-ref genotypes to infer at sites not present in a panel  Default value: 0.

--pedigree,-ped:File          Pedigree file for determining the population "founders"  Default value: null.

--population-callset,-population:FeatureInput
                              Callset to use in calculating genotype priors  Default value: null.

--QUIET:Boolean               Whether to suppress job-summary info on System.err.  Default value: false. Possible
                              values: {true, false}

--read-filter,-RF:String      Read filters to be applied before analysis  This argument may be specified 0 or more
                              times. Default value: null. Possible Values: {AlignmentAgreesWithHeaderReadFilter,
                              AllowAllReadsReadFilter, AmbiguousBaseReadFilter, CigarContainsNoNOperator,
                              FirstOfPairReadFilter, FragmentLengthReadFilter, GoodCigarReadFilter,
                              HasReadGroupReadFilter, IntervalOverlapReadFilter, LibraryReadFilter, MappedReadFilter,
                              MappingQualityAvailableReadFilter, MappingQualityNotZeroReadFilter,
                              MappingQualityReadFilter, MatchingBasesAndQualsReadFilter, MateDifferentStrandReadFilter,
                              MateOnSameContigOrNoMappedMateReadFilter, MateUnmappedAndUnmappedReadFilter,
                              MetricsReadFilter, NonChimericOriginalAlignmentReadFilter,
                              NonZeroFragmentLengthReadFilter, NonZeroReferenceLengthAlignmentReadFilter,
                              NotDuplicateReadFilter, NotOpticalDuplicateReadFilter, NotSecondaryAlignmentReadFilter,
                              NotSupplementaryAlignmentReadFilter, OverclippedReadFilter, PairedReadFilter,
                              PassesVendorQualityCheckReadFilter, PlatformReadFilter, PlatformUnitReadFilter,
                              PrimaryLineReadFilter, ProperlyPairedReadFilter, ReadGroupBlackListReadFilter,
                              ReadGroupReadFilter, ReadLengthEqualsCigarLengthReadFilter, ReadLengthReadFilter,
                              ReadNameReadFilter, ReadStrandFilter, SampleReadFilter, SecondOfPairReadFilter,
                              SeqIsStoredReadFilter, ValidAlignmentEndReadFilter, ValidAlignmentStartReadFilter,
                              WellformedReadFilter}

--read-index,-read-index:String
                              Indices to use for the read inputs. If specified, an index must be provided for every read
                              input and in the same order as the read inputs. If this argument is not specified, the
                              path to the index for each input will be inferred automatically.  This argument may be
                              specified 0 or more times. Default value: null.

--read-validation-stringency,-VS:ValidationStringency
                              Validation stringency for all SAM/BAM/CRAM/SRA files read by this program.  The default
                              stringency value SILENT can improve performance when processing a BAM file in which
                              variable-length data (read, qualities, tags) do not otherwise need to be decoded.  Default
                              value: SILENT. Possible values: {STRICT, LENIENT, SILENT}

--sample-ploidy,-ploidy:Integer
                              Ploidy (number of chromosomes) per sample. For pooled data, set to (Number of samples in
                              each pool * Sample Ploidy).  Default value: 2.

--seconds-between-progress-updates,-seconds-between-progress-updates:Double
                              Output traversal statistics every time this many seconds elapse  Default value: 10.0.

--sequence-dictionary,-sequence-dictionary:String
                              Use the given sequence dictionary as the master/canonical sequence dictionary.  Must be a
                              .dict file.  Default value: null.

--sites-only-vcf-output:Boolean
                              If true, don't emit genotype fields when writing vcf file output.  Default value: false.
                              Possible values: {true, false}

--standard-min-confidence-threshold-for-calling,-stand-call-conf:Double
                              The minimum phred-scaled confidence threshold at which variants should be called  Default
                              value: 30.0.

--tmp-dir:GATKPathSpecifier   Temp directory to use.  Default value: null.

--tumor-lod-to-emit,-emit-lod:Double
                              LOD threshold to emit variant to VCF.  Default value: 3.5.

--use-jdk-deflater,-jdk-deflater:Boolean
                              Whether to use the JdkDeflater (as opposed to IntelDeflater)  Default value: false.
                              Possible values: {true, false}

--use-jdk-inflater,-jdk-inflater:Boolean
                              Whether to use the JdkInflater (as opposed to IntelInflater)  Default value: false.
                              Possible values: {true, false}

--use-new-qual-calculator,-new-qual:Boolean
                              Use the new AF model instead of the so-called exact model  Default value: true. Possible
                              values: {true, false}

--use-old-qual-calculator,-old-qual:Boolean
                              Use the old AF model  Default value: false. Possible values: {true, false}

--verbosity,-verbosity:LogLevel
                              Control verbosity of logging.  Default value: INFO. Possible values: {ERROR, WARNING,
                              INFO, DEBUG}

--version:Boolean             display the version number for this tool  Default value: false. Possible values: {true,
                              false}


Advanced Arguments:

--disable-tool-default-annotations,-disable-tool-default-annotations:Boolean
                              Disable all tool default annotations  Default value: false. Possible values: {true, false}

--disable-tool-default-read-filters,-disable-tool-default-read-filters:Boolean
                              Disable all tool default read filters (WARNING: many tools will not function correctly
                              without their default read filters on)  Default value: false. Possible values: {true,
                              false}

--enable-all-annotations:Boolean
                              Use all possible annotations (not for the faint of heart)  Default value: false. Possible
                              values: {true, false}

--input-prior:Double          Input prior for calls  This argument may be specified 0 or more times. Default value:
                              null.

--max-alternate-alleles:Integer
                              Maximum number of alternate alleles to genotype  Default value: 6.

--max-genotype-count:Integer  Maximum number of genotypes to consider at any site  Default value: 1024.

--only-output-calls-starting-in-intervals:Boolean
                              Restrict variant output to sites that start within provided intervals  Default value:
                              false. Possible values: {true, false}

--showHidden,-showHidden:Boolean
                              display hidden arguments  Default value: false. Possible values: {true, false}
#</opt_g>
#</option detail>

