#!/bin/bash

explanation='
test tool 3
'
inputdef='
input_1:directory:FASTQ(.gz):*.fastq,*.fq,*.fastq.gz,*.fq.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1#"

export IM_TEST="rockylinux:9"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

env > env.txt
uname -a > uname.txt

cd $input_1

r1=`ls |egrep "[.]f(ast|)q([.]gz|)$" || echo ""`

if [ "$r1" = "" ]; then echo Place fastq or fastq.gz files in this folder; false; fi

DO_TEST ls > output.txt
DO_TEST sleep 6
touch sleep60.txt

for i in `seq 1 10`;do
 echo "$ENV_TEST sleep 5; echo fin"
done | DOPARALLELONE
WAITPARALLEL

bash "$scriptdir"/ZZZ~wait-10sec ./

PP_DO_CHILD ZZZ~wait-10sec ./

PP_ENV_CHILD ZZZ~wait-10sec ./ | DOPARALLELONE
WAITPARALLEL

post_processing
#<option detail>
#<opt_c>
#</opt_c>
#</option detail>

