#!/bin/bash

explanation='
test tool
'
inputdef='
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
'
runcmd="$0 -c #opt_c# -m #opt_m#"

export IM_TEST="rockylinux:9"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

echo "Hello World!"

post_processing
#<option detail>
#<opt_c>
#</opt_c>
#</option detail>

