#!/bin/bash

explanation='
test tool 3
'
inputdef='
input_1:directory:FASTQ(.gz):*.fastq,*.fq,*.fastq.gz,*.fq.gz
'
optiondef='
opt_c:cpu threads:8
opt_m:memory limit (GB):32
'
runcmd="$0 -c #opt_c# -m #opt_m# #input_1#"

export IM_TEST="centos:7"

source $(dirname `readlink -f $0 || echo $0`)/common.sh

set -eux
set -o pipefail

pwd
cd $input_1
pwd

r1=`ls |egrep "[.]f(ast|)q([.]gz|)$" || echo ""`

if [ "$r1" = "" ]; then echo Place fastq or fastq.gz files in this folder; exit; fi
DO_TEST ls -lh "$r1"
DO_TEST touch test.txt

touch sleepb10.txt
sleep 10
touch sleepa10.txt

post_processing
#<option detail>
#<opt_c>
#</opt_c>
#</option detail>

